In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("trans.csv", sep=';')
df

C:\Users\Salur\AppData\Local\Temp\ipykernel_2772\3266114813.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("trans.csv", sep=';')

,trans_id,account_id,date,type,operation,amount,balance,k_symbol,bank,account
0,695247,2378,930101,PRIJEM,VKLAD,700.0,700.0,NaN,NaN,NaN
1,171812,576,930101,PRIJEM,VKLAD,900.0,900.0,NaN,NaN,NaN
2,207264,704,930101,PRIJEM,VKLAD,1000.0,1000.0,NaN,NaN,NaN
3,1117247,3818,930101,PRIJEM,VKLAD,600.0,600.0,NaN,NaN,NaN
4,579373,1972,930102,PRIJEM,VKLAD,400.0,400.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1056315,3626622,2906,981231,PRIJEM,NaN,62.3,13729.4,UROK,NaN,NaN
1056316,3627616,2935,981231,PRIJEM,NaN,81.3,19544.9,UROK,NaN,NaN
1056317,3625403,2869,981231,PRIJEM,NaN,60.2,14638.2,UROK,NaN,NaN
1056318,3626683,2907,981231,PRIJEM,NaN,107.5,23453.0,UROK,NaN,NaN
1056319,3626540,2902,981231,PRIJEM,NaN,164.1,41642.9,UROK,NaN,NaN

In [3]:
import os
os.getcwd()

'C:\\Users\\Salur'

In [5]:
df.head()

,trans_id,account_id,date,type,operation,amount,balance,k_symbol,bank,account
0,695247,2378,930101,PRIJEM,VKLAD,700.0,700.0,NaN,NaN,NaN
1,171812,576,930101,PRIJEM,VKLAD,900.0,900.0,NaN,NaN,NaN
2,207264,704,930101,PRIJEM,VKLAD,1000.0,1000.0,NaN,NaN,NaN
3,1117247,3818,930101,PRIJEM,VKLAD,600.0,600.0,NaN,NaN,NaN
4,579373,1972,930102,PRIJEM,VKLAD,400.0,400.0,NaN,NaN,NaN

In [6]:
df = df.drop(columns= ['balance','k_symbol','bank','account']) 
df.head()

   trans_id  account_id    date    type operation  amount
0    695247        2378  930101  PRIJEM     VKLAD   700.0
1    171812         576  930101  PRIJEM     VKLAD   900.0
2    207264         704  930101  PRIJEM     VKLAD  1000.0
3   1117247        3818  930101  PRIJEM     VKLAD   600.0
4    579373        1972  930102  PRIJEM     VKLAD   400.0

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1056320 entries, 0 to 1056319
Data columns (total 6 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   trans_id    1056320 non-null  int64
 1   account_id  1056320 non-null  int64
 2   date        1056320 non-null  int64
 3   type        1056320 non-null  object
 4   operation   873206 non-null   object
 5   amount      1056320 non-null  float64
dtypes: float64(1), int64(3), object(2)
memory usage: 48.4+ MB

In [7]:
df['date'] = pd.to_datetime(df['date'], format='%y%m%d') 
df.head()

   trans_id  account_id       date    type operation  amount
0    695247        2378 1993-01-01  PRIJEM     VKLAD   700.0
1    171812         576 1993-01-01  PRIJEM     VKLAD   900.0
2    207264         704 1993-01-01  PRIJEM     VKLAD  1000.0
3   1117247        3818 1993-01-01  PRIJEM     VKLAD   600.0
4    579373        1972 1993-01-02  PRIJEM     VKLAD   400.0

In [8]:
df['type'].unique()

array(['PRIJEM', 'VYDAJ', 'VYBER'], dtype=object)

In [9]:
df =df[df['type']=='PRIJEM']
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 405083 entries, 0 to 1056319
Data columns (total 6 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   trans_id    405083 non-null  int64
 1   account_id  405083 non-null  int64
 2   date        405083 non-null  datetime64[ns]
 3   type        405083 non-null  object
 4   operation   221969 non-null  object
 5   amount      405083 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 21.6+ MB

In [10]:
rfm_df = df.groupby('account_id').agg({'amount' : 'sum' , 'date' : ['count','max']})
rfm_df.head()

               amount  date
                  sum count        max
account_id
1            194320.5   102 1998-12-31
2           1597053.5   152 1998-12-31
3            173059.0    46 1998-12-31
4            192346.0    65 1998-12-31
5             97485.0    35 1998-12-31

In [11]:
rfm_df.columns = ['Monetary', 'Frequency', 'Last_Date']
rfm_df.head(10)

             Monetary  Frequency  Last_Date
account_id
1            194320.5        102 1998-12-31
2           1597053.5        152 1998-12-31
3            173059.0         46 1998-12-31
4            192346.0         65 1998-12-31
5             97485.0         35 1998-12-31
6            347617.5         99 1998-12-31
7            630267.9         51 1998-12-31
8            892761.7         84 1998-12-31
9            360155.9        183 1998-12-31
10           549950.3         59 1998-12-31

In [12]:
analiz_tarihi = df['date'].max() + pd.Timedelta(days=1)
rfm_df['Recency'] = (analiz_tarihi - rfm_df['Last_Date']).dt.days
rfm_df.tail(10)

             Monetary  Frequency  Last_Date  Recency
account_id
11317       1129292.1         54 1998-12-31        1
11320       1276943.7        199 1998-12-07       25
11325        489156.9         58 1998-06-30      185
11327        318617.2         30 1998-12-31        1
11328        695203.0         63 1998-12-31        1
11333       1677057.6        183 1998-12-31        1
11349       1995675.2         91 1998-12-31        1
11359       1511641.2        104 1998-12-31        1
11362        684270.7         81 1998-12-31        1
11382       1352418.5        121 1998-12-31        1

In [13]:
rfm_df = rfm_df.drop(columns='Last_Date') 
rfm_df.head()

             Monetary  Frequency  Recency
account_id
1            194320.5        102        1
2           1597053.5        152        1
3            173059.0         46        1
4            192346.0         65        1
5             97485.0         35        1

In [14]:
rfm_df['Recency_Score'] = pd.qcut(rfm_df['Recency'].rank(method='first'), q=5, labels=[5,4,3,2,1])    #rank methodu 5 e tam bölünmediği için ekledik, bölünüyomuş gibi yapsın diye
rfm_df['Frequency_Score'] = pd.qcut(rfm_df['Frequency'].rank(method='first'), q=5, labels=[1,2,3,4,5])
rfm_df['Monetary_Score'] = pd.qcut(rfm_df['Monetary'].rank(method='first'), q=5, labels=[1,2,3,4,5])
rfm_df.head()

,Monetary,Frequency,Recency,Recency_Score,Frequency_Score,Monetary_Score
account_id,,,,,,
1,194320.5,102,1,5,4,2
2,1597053.5,152,1,5,5,5
3,173059.0,46,1,5,1,1
4,192346.0,65,1,5,2,2
5,97485.0,35,1,5,1,1

In [15]:
rfm_df['Recency_Score']= rfm_df['Recency_Score'].astype(str) 
rfm_df['Frequency_Score']= rfm_df['Frequency_Score'].astype(str)    # skorları yan yana yazdırabilmek için str yaptık, toplamasın yan yana yazsın diye
rfm_df['Monetary_Score']= rfm_df['Monetary_Score'].astype(str)   

rfm_df['RFM_skoru'] = rfm_df['Recency_Score'] + rfm_df['Frequency_Score'] + rfm_df['Monetary_Score'] 
rfm_df.head()

,Monetary,Frequency,Recency,Recency_Score,Frequency_Score,Monetary_Score,RFM_skoru
account_id,,,,,,,
1,194320.5,102,1,5,4,2,542
2,1597053.5,152,1,5,5,5,555
3,173059.0,46,1,5,1,1,511
4,192346.0,65,1,5,2,2,522
5,97485.0,35,1,5,1,1,511

In [16]:
rfm_df['RF_Score'] = rfm_df['Recency_Score'] + rfm_df['Frequency_Score'] 
rfm_df.head()    # rfm de kategoriler genelde rf ye göre yapılır, 5x5 lik matrise uysun diye, m si daha sonra yine kullanılır.

,Monetary,Frequency,Recency,Recency_Score,Frequency_Score,Monetary_Score,RFM_skoru,RF_Score
account_id,,,,,,,,
1,194320.5,102,1,5,4,2,542,54
2,1597053.5,152,1,5,5,5,555,55
3,173059.0,46,1,5,1,1,511,51
4,192346.0,65,1,5,2,2,522,52
5,97485.0,35,1,5,1,1,511,51

In [29]:
seg_map = {
    r'[1-2][1-2]': 'Uyuyanlar',
    r'[1-2][3-4]': 'Riskli',
    r'[1-2]5': 'Kaybedilemez',
    r'3[1-2]': 'Uyku_Adayi',
    r'33': 'Dikkat_Gereken',
    r'[3-4][4-5]': 'Sadik_Musteriler',
    r'41': 'Umut_Veren',
    r'51': 'Yeni_Musteriler',
    r'[4-5][2-3]': 'Potansiyel_Sadik',
    r'5[4-5]': 'Sampiyonlar'
}

rfm_df['Segment']= rfm_df['RF_Score'].replace(seg_map, regex=True) 
rfm_df.tail(10)

,Monetary,Frequency,Recency,Recency_Score,Frequency_Score,Monetary_Score,RFM_skoru,RF_Score,Segment
account_id,,,,,,,,,
11317,1129292.1,54,1,1,2,4,124,12,Uyuyanlar
11320,1276943.7,199,25,1,5,5,155,15,Kaybedilemez
11325,489156.9,58,185,1,2,3,123,12,Uyuyanlar
11327,318617.2,30,1,1,1,2,112,11,Uyuyanlar
11328,695203.0,63,1,1,2,4,124,12,Uyuyanlar
11333,1677057.6,183,1,1,5,5,155,15,Kaybedilemez
11349,1995675.2,91,1,1,3,5,135,13,Riskli
11359,1511641.2,104,1,1,4,5,145,14,Riskli
11362,684270.7,81,1,1,3,4,134,13,Riskli
11382,1352418.5,121,1,1,4,5,145,14,Riskli

In [19]:
rfm_df.groupby('Segment').agg({'Recency': ['count','mean'] , 'Frequency': 'mean','Monetary' : 'mean'})  
# segmentlerin özetini çıkardık, hangi segment bize ne katıyor.

                 Recency              Frequency      Monetary
                   count       mean        mean          mean
Segment
Dikkat_Gereken       171   1.000000   81.584795  6.238426e+05
Kaybedilemez         377   2.453581  164.111406  1.533403e+06
Potansiyel_Sadik     720   1.000000   70.522222  5.161606e+05
Riskli               721   3.073509   98.081831  8.661164e+05
Sadik_Musteriler     714   1.000000  132.789916  9.843365e+05
Sampiyonlar          361   1.000000  134.709141  9.761602e+05
Umut_Veren           169   1.000000   38.485207  2.517583e+05
Uyku_Adayi           381   1.000000   48.099738  3.518885e+05
Uyuyanlar            702  19.085470   46.360399  3.867305e+05
Yeni_Musteriler      184   1.000000   37.782609  2.352457e+05

In [23]:
total_customers = rfm_df.shape[0]
total_monetary = rfm_df['Monetary'].sum()
pareto_df = rfm_df.groupby('Segment').agg(Müşteri_Sayısı=('Recency', 'count'),Toplam_Ciro=('Monetary', 'sum')).reset_index()

pareto_df

            Segment  Müşteri_Sayısı  Toplam_Ciro
0    Dikkat_Gereken             171  106677080.2
1      Kaybedilemez             377  578093067.0
2  Potansiyel_Sadik             720  371635603.7
3            Riskli             721  624469899.7
4  Sadik_Musteriler             714  702816258.2
5       Sampiyonlar             361  352393846.5
6        Umut_Veren             169   42547148.6
7        Uyku_Adayi             381  134069531.2
8         Uyuyanlar             702  271484789.2
9   Yeni_Musteriler             184   43285200.2

In [28]:
pareto_df['Müşteri_yüzdesi'] = (pareto_df['Müşteri_Sayısı']/ total_customers) *100
pareto_df['Ciro_yüzdesi'] = (pareto_df['Toplam_Ciro']/ total_monetary) * 100 

pareto_df = pareto_df.sort_values(by='Ciro_yüzdesi', ascending=False) 
pareto_df

,Segment,Müşteri_Sayısı,Toplam_Ciro,Müşteri_yüzdesi,Ciro_yüzdesi
4,Sadik_Musteriler,714,702816258.2,15.866667,21.776058
3,Riskli,721,624469899.7,16.022222,19.348574
1,Kaybedilemez,377,578093067.0,8.377778,17.911635
2,Potansiyel_Sadik,720,371635603.7,16.000000,11.514757
5,Sampiyonlar,361,352393846.5,8.022222,10.918570
8,Uyuyanlar,702,271484789.2,15.600000,8.411684
7,Uyku_Adayi,381,134069531.2,8.466667,4.154010
0,Dikkat_Gereken,171,106677080.2,3.800000,3.305282
9,Yeni_Musteriler,184,43285200.2,4.088889,1.341149
6,Umut_Veren,169,42547148.6,3.755556,1.318281

In [30]:
ozet_tablo = rfm_df.groupby('Segment').agg({
    'Recency': ['count', 'mean'], 
    'Frequency': 'mean', 
    'Monetary': 'mean'
})


ozet_tablo.to_excel('RFM_Ozet_Tablosu.xlsx')


pareto_df.to_excel('Pareto_Analizi.xlsx', index=False)